---
apiVersion: app/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  labels:
    app: frontend-app
spec: 
  template:
    metadata: 
      labels: 
        app: frontend-app
    spec:
      containers:
      - name: frontend-ctr        
...      